[build]
  command = "CI= yarn build"
  publish = "packages/web/build"
  functions = "packages/api/dist"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/index"
  status = 200

[dev]
  command = "yarn dev"
  port = 8888
  targetPort = 3000
  publish = "packages/web/build" 
  autoLaunch = true
  framework = "#custom"