name = "api"
type = "webpack"
account_id = "48c0efd6174556f0b34ab86da218c6f9"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [ 
         { binding = "STORE", preview_id = "e05737c442bb4b9bb6cda9bc456696c8", id = "50ae0e830cec46bcbb3c19415abb9c05" }
]